
POST http://localhost:3000/fetch
Content-Type: application/json

{
  "filter": {},
  "expense": {"contract":  0}

}

###

GET http://localhost:3000/top-spenders
Content-Type: application/json

###


GET http://localhost:3000/avg-group
Content-Type: application/json


###


GET http://localhost:3000/sum-group
Content-Type: application/json

###


GET http://localhost:3000/fetch-transactions
Content-Type: application/json


###


GET http://localhost:3000/sum-total
Content-Type: application/json
